/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'Paul' at '3/27/17 8:13 AM' with Gradle 3.2.1
 *
 * @author Paul, @date 3/27/17 8:13 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
