/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Paul' at '3/27/17 8:13 AM' with Gradle 3.2.1
 *
 * @author Paul, @date 3/27/17 8:13 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
